In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns

Importamos los datos

In [2]:
dataframe = pd.read_csv("data.csv")
print(dataframe)

        Periodo      ID Especialidad del momento Codigo curso  \
0      201220.0   135.0                     INGE      ICE3210
1      201220.0   135.0                     INGE      ICE3210
2      201220.0   135.0                     INGE      ING2152
3      201220.0   135.0                     INGE      ING2152
4      201220.0   135.0                     INGE      ING3520
5      201220.0   135.0                     INGE      ING3520
6      201220.0   135.0                     INGE      IOC3150
7      201220.0   135.0                     INGE      IOC3150
8      201220.0   916.0                     INGO      CEG2006
9      201220.0   916.0                     INGO      CEG2006
10     201220.0   916.0                     INGO      ING5230
11     201220.0   916.0                     INGO      ING5230
12     201220.0   916.0                     INGO      ING5411
13     201220.0   916.0                     INGO      ING5411
14     201220.0   916.0                     INGO      ING5510
15     201220.0   916.0                     INGO      ING5510
16     201220.0   916.0                     INGO      ING6410
17     201220.0   916.0                     INGO      ING6410
18     201220.0   916.0                     INGO      IOC4110
19     201220.0   916.0                     INGO      IOC4110
20     201220.0   916.0                     INGO      IOC4140
21     201220.0   916.0                     INGO      IOC4140
22     201220.0  2141.0                      NaN      ING6110
23     201220.0  2141.0                      NaN      ING6110
24     201220.0  2141.0                      NaN      ING6210
25     201220.0  2141.0                      NaN      ING6210
26     201220.0   816.0                     INGO      CEG1010
27     201220.0   816.0                     INGO      CEG1010
28     201220.0   816.0                     INGO      FRM1100
29     201220.0   816.0                     INGO      FRM1100
...         ...     ...                      ...          ...
32419       NaN     NaN                      NaN          NaN
32420       NaN     NaN                      NaN          NaN
32421       NaN     NaN                      NaN          NaN
32422       NaN     NaN                      NaN          NaN
32423       NaN     NaN                      NaN          NaN
32424       NaN     NaN                      NaN          NaN
32425       NaN     NaN                      NaN          NaN
32426       NaN     NaN                      NaN          NaN
32427       NaN     NaN                      NaN          NaN
32428       NaN     NaN                      NaN          NaN
32429       NaN     NaN                      NaN          NaN
32430       NaN     NaN                      NaN          NaN
32431       NaN     NaN                      NaN          NaN
32432       NaN     NaN                      NaN          NaN
32433       NaN     NaN                      NaN          NaN
32434       NaN     NaN                      NaN          NaN
32435       NaN     NaN                      NaN          NaN
32436       NaN     NaN                      NaN          NaN
32437       NaN     NaN                      NaN          NaN
32438       NaN     NaN                      NaN          NaN
32439       NaN     NaN                      NaN          NaN
32440       NaN     NaN                      NaN          NaN
32441       NaN     NaN                      NaN          NaN
32442       NaN     NaN                      NaN          NaN
32443       NaN     NaN                      NaN          NaN
32444       NaN     NaN                      NaN          NaN
32445       NaN     NaN                      NaN          NaN
32446       NaN     NaN                      NaN          NaN
32447       NaN     NaN                      NaN          NaN
32448       NaN     NaN                      536          NaN

                                            Nombre curso Nota
0                                  ANALISIS DE CIRCUITOS  5.1
1                                  ANALISIS DE CIRCUITOS  5.1
2                                   MECANICA RACIONAL II  5.6
3                                   MECANICA RACIONAL II  5.6
4                                   ESTADISTICA APLICADA  5.5
5                                   ESTADISTICA APLICADA  5.5
6                                  MATEMATICAS APLICADAS  5.2
7                                  MATEMATICAS APLICADAS  5.2
8                                DE BEETHOVEN A PIAZZOLA  6.1
9                                DE BEETHOVEN A PIAZZOLA  6.1
10                                      ORAL PERFORMANCE  5.1
11                                      ORAL PERFORMANCE  5.1
12                                      CRITICAL THOUGHT  5.7
13                                      CRITICAL THOUGHT  5.7
14                                         MICROECONOMIA  5.9
15                                         MICROECONOMIA  5.9
16                    PROFESSIONAL PAPERS IN ENGINEERING  5.8
17                    PROFESSIONAL PAPERS IN ENGINEERING  5.8
18                          MECANICA DE FLUIDOS APLICADA  5.4
19                          MECANICA DE FLUIDOS APLICADA  5.4
20                                SISTEMA DE TRANSPORTES  5.3
21                                SISTEMA DE TRANSPORTES  5.3
22                                   GESTION ESTRATEGICA  5.8
23                                   GESTION ESTRATEGICA  5.8
24                                               MEMORIA  6.5
25                                               MEMORIA  6.5
26     HISTORIA DE LA UNIVERSIDAD:DE SOCRATES A WIKIP...  5.4
27     HISTORIA DE LA UNIVERSIDAD:DE SOCRATES A WIKIP...  5.4
28                                            TEOLOGIA I  4.3
29                                            TEOLOGIA I  4.3
...                                                  ...  ...
32419                                                NaN  NaN
32420                                                NaN  NaN
32421                                                NaN  NaN
32422                                                NaN  NaN
32423                                                NaN  NaN
32424                                                NaN  NaN
32425                                                NaN  NaN
32426                                                NaN  NaN
32427                                                NaN  NaN
32428                                                NaN  NaN
32429                                                NaN  NaN
32430                                                NaN  NaN
32431                                                NaN  NaN
32432                                                NaN  NaN
32433                                                NaN  NaN
32434                                                NaN  NaN
32435                                                NaN  NaN
32436                                                NaN  NaN
32437                                                NaN  NaN
32438                                                NaN  NaN
32439                                                NaN  NaN
32440                                                NaN  NaN
32441                                                NaN  NaN
32442                                                NaN  NaN
32443                                                NaN  NaN
32444                                                NaN  NaN
32445                                                NaN  NaN
32446                                                NaN  NaN
32447                                                NaN  NaN
32448                                                NaN  NaN

[32449 rows x 6 columns]

Filtramos las filas que tengan notas nulas y los datos duplicados.  
Transformamos ademas la nota a entero eliminando las filas que no tengan una nota numérica, y el semestre a string dado a que no nos importa su valor numérico.

In [3]:
dataframe = dataframe[pd.to_numeric(dataframe['Nota'], errors='coerce').notnull()]
dataframe['Nota'] = dataframe['Nota'].apply(float)
dataframe = dataframe.drop_duplicates(subset=['Periodo', 'ID', 'Codigo curso'])
dataframe['Periodo'] = dataframe['Periodo'].astype(int).apply(str)
dataframe['ID'] = dataframe['ID'].astype(int)
print(dataframe)

      Periodo       ID Especialidad del momento Codigo curso  \
0      201220      135                     INGE      ICE3210
2      201220      135                     INGE      ING2152
4      201220      135                     INGE      ING3520
6      201220      135                     INGE      IOC3150
8      201220      916                     INGO      CEG2006
10     201220      916                     INGO      ING5230
12     201220      916                     INGO      ING5411
14     201220      916                     INGO      ING5510
16     201220      916                     INGO      ING6410
18     201220      916                     INGO      IOC4110
20     201220      916                     INGO      IOC4140
22     201220     2141                      NaN      ING6110
24     201220     2141                      NaN      ING6210
26     201220      816                     INGO      CEG1010
28     201220      816                     INGO      FRM1100
30     201220      816                     INGO      ING2121
32     201220      816                     INGO      ING2140
34     201220      816                     INGO      INM0002
36     201220   138126                     INGI      ING5230
38     201220   138126                     INGI      ING6210
40     201220   931535                     INGI      ING3120
42     201220   931535                     INGI      ING4130
44     201220  6615148                     INGO      ING3120
46     201220  6615148                     INGO      ING5411
48     201220  6615148                     INGO      ING5510
50     201220  6615148                     INGO      IOC4130
52     201220      695                     INGO      ING5510
54     201220      695                     INGO      IOC3150
56     201220      695                     INGO      IOC4140
58     201220      695                     INGO      IOC5320
...       ...      ...                      ...          ...
32369  201520     1519                     INGI      ING4130
32370  201520     1968                     INGI      ING1140
32371  201520     1968                     INGI      ING1150
32372  201520     1968                     INGI      ING1310
32373  201520     1968                     INGI      ING1610
32374  201520     1968                     INGI      ING2140
32375  201520     2003                      ING      ING1120
32376  201520     2003                      ING      ING1131
32377  201520     2003                      ING      ING1610
32378  201520     2003                      ING      ING2140
32379  201520     2003                      ING      ING2210
32380  201520     1702                     INGI      ING1150
32381  201520     1702                     INGI      ING2112
32382  201520     1702                     INGI      ING2210
32383  201520     1517                     INGI      ING2131
32384  201520     1517                     INGI      ING2152
32385  201520     1517                     INGI      ING2160
32386  201520     1517                     INGI      ING3510
32387  201520     2131                     INGI      ING1111
32388  201520     2131                     INGI      ING1120
32389  201520     2131                     INGI      ING1131
32390  201520     2131                     INGI      ING1310
32391  201520     2131                     INGI      ING1610
32392  201520     1964                     INGC      ING1111
32393  201520     1964                     INGC      ING1131
32394  201520     1964                     INGC      ING1140
32395  201520     1964                     INGC      ING1310
32396  201520     1964                     INGC      ING1610
32397  201520     2006                     INGE      ING1131
32398  201520     2006                     INGE      ING1140

                                            Nombre curso  Nota
0                                  ANALISIS DE CIRCUITOS   5.1
2                                   MECANICA RACIONAL II   5.6
4                                   ESTADISTICA APLICADA   5.5
6                                  MATEMATICAS APLICADAS   5.2
8                                DE BEETHOVEN A PIAZZOLA   6.1
10                                      ORAL PERFORMANCE   5.1
12                                      CRITICAL THOUGHT   5.7
14                                         MICROECONOMIA   5.9
16                    PROFESSIONAL PAPERS IN ENGINEERING   5.8
18                          MECANICA DE FLUIDOS APLICADA   5.4
20                                SISTEMA DE TRANSPORTES   5.3
22                                   GESTION ESTRATEGICA   5.8
24                                               MEMORIA   6.5
26     HISTORIA DE LA UNIVERSIDAD:DE SOCRATES A WIKIP...   5.4
28                                            TEOLOGIA I   4.3
30                                   MECANICA RACIONAL I   4.1
32                                        ALGEBRA LINEAL   5.0
34                  INGLES PARA PROPOSITOS ACADEMICOS II   5.7
36                                      ORAL PERFORMANCE   5.8
38                                               MEMORIA   7.0
40                                   MECANICA DE FLUIDOS   4.2
42                              BASES DE DATOS APLICADAS   1.0
44                                   MECANICA DE FLUIDOS   5.0
46                                      CRITICAL THOUGHT   4.2
48                                         MICROECONOMIA   1.0
50                     GEOLOGIA APLICADA A LA INGENIERIA   5.3
52                                         MICROECONOMIA   4.6
54                                 MATEMATICAS APLICADAS   4.0
56                                SISTEMA DE TRANSPORTES   4.5
58                                   CONSTRUCCION PESADA   5.7
...                                                  ...   ...
32369                           BASES DE DATOS APLICADAS   4.1
32370                                  FISICA GENERAL II   4.3
32371                                          CALCULO I   4.3
32372                      INTRODUCCION A LA COMPUTACION   3.9
32373                            ANTROPOLOGIA FILOSOFICA   4.6
32374                                     ALGEBRA LINEAL   4.8
32375                                   FISICA GENERAL I   4.0
32376                     GEOMETRIA ANALITICA E INTRODUC   4.0
32377                            ANTROPOLOGIA FILOSOFICA   3.7
32378                                     ALGEBRA LINEAL   2.0
32379                                    QUIMICA GENERAL   4.8
32380                                          CALCULO I   4.4
32381                                              ETICA   4.4
32382                                    QUIMICA GENERAL   5.3
32383                                  ELECTROMAGNETISMO   5.4
32384                               MECANICA RACIONAL II   5.5
32385                           TEORIA DE PROBABILIDADES   4.0
32386                     INTRODUCCION A LA OPTIMIZACION   4.3
32387                                            ALGEBRA   3.4
32388                                   FISICA GENERAL I   3.1
32389                     GEOMETRIA ANALITICA E INTRODUC   3.6
32390                      INTRODUCCION A LA COMPUTACION   2.8
32391                            ANTROPOLOGIA FILOSOFICA   5.1
32392                                            ALGEBRA   4.3
32393                     GEOMETRIA ANALITICA E INTRODUC   3.5
32394                                  FISICA GENERAL II   3.5
32395                      INTRODUCCION A LA COMPUTACION   5.8
32396                            ANTROPOLOGIA FILOSOFICA   4.8
32397                     GEOMETRIA ANALITICA E INTRODUC   4.0
32398                                  FISICA GENERAL II   4.0

[28167 rows x 6 columns]

Filtramos los alumnos sin especialidad o con especialidad nula pues no nos interesan para entrenamiento, validación o testeo, y eliminamos la columna con el nombre del ramo.  
Guardamos los ramos realizados por alumnos sin especialidad, para luego eliminar las filas que tengan ramos fuera de este conjunto.

In [4]:
nullframe = dataframe[pd.isnull(dataframe['Especialidad del momento'])]
ingframe = dataframe[(dataframe['Especialidad del momento'] == 'ING')]
nospecialtyframe = pd.concat([nullframe,ingframe])
dataframe = dataframe[pd.notnull(dataframe['Especialidad del momento'])]
dataframe = dataframe[(dataframe['Especialidad del momento'] != 'ING')]
dataframe = dataframe.drop(columns=['Nombre curso'])
basic_courses = nospecialtyframe['Codigo curso'].unique()
dataframe = dataframe[dataframe['Codigo curso'].isin(basic_courses)].reset_index().drop(columns=['index'])
print (dataframe)

      Periodo        ID Especialidad del momento Codigo curso  Nota
0      201220       135                     INGE      ING2152   5.6
1      201220       135                     INGE      ING3520   5.5
2      201220       135                     INGE      IOC3150   5.2
3      201220       916                     INGO      CEG2006   6.1
4      201220       916                     INGO      ING5230   5.1
5      201220       916                     INGO      ING5510   5.9
6      201220       916                     INGO      ING6410   5.8
7      201220       916                     INGO      IOC4140   5.3
8      201220       816                     INGO      CEG1010   5.4
9      201220       816                     INGO      FRM1100   4.3
10     201220       816                     INGO      ING2121   4.1
11     201220       816                     INGO      ING2140   5.0
12     201220       816                     INGO      INM0002   5.7
13     201220    138126                     INGI      ING5230   5.8
14     201220    138126                     INGI      ING6210   7.0
15     201220    931535                     INGI      ING4130   1.0
16     201220   6615148                     INGO      ING5510   1.0
17     201220   6615148                     INGO      IOC4130   5.3
18     201220       695                     INGO      ING5510   4.6
19     201220       695                     INGO      IOC3150   4.0
20     201220       695                     INGO      IOC4140   4.5
21     201220   7164276                     INGE      ICE0665   5.2
22     201220   9405046                     INGI      CEG1000   6.7
23     201220   9405046                     INGI      ING1111   3.0
24     201220   9405046                     INGI      ING1120   4.5
25     201220   9405046                     INGI      ING1131   2.0
26     201220   9405046                     INGI      ING1310   1.6
27     201220   9405046                     INGI      ING1610   6.8
28     201220  13078358                     INGO      ING6520   5.3
29     201220  13078358                     INGO      IOC0651   6.4
...       ...       ...                      ...          ...   ...
19537  201520      1959                     INGO      ING1131   4.4
19538  201520      1959                     INGO      ING1310   6.0
19539  201520      1959                     INGO      ING1610   3.8
19540  201520      1959                     INGO      ING2140   3.7
19541  201520      1519                     INGI      ING1150   4.8
19542  201520      1519                     INGI      ING4130   4.1
19543  201520      1968                     INGI      ING1140   4.3
19544  201520      1968                     INGI      ING1150   4.3
19545  201520      1968                     INGI      ING1310   3.9
19546  201520      1968                     INGI      ING1610   4.6
19547  201520      1968                     INGI      ING2140   4.8
19548  201520      1702                     INGI      ING1150   4.4
19549  201520      1702                     INGI      ING2112   4.4
19550  201520      1702                     INGI      ING2210   5.3
19551  201520      1517                     INGI      ING2131   5.4
19552  201520      1517                     INGI      ING2152   5.5
19553  201520      1517                     INGI      ING2160   4.0
19554  201520      1517                     INGI      ING3510   4.3
19555  201520      2131                     INGI      ING1111   3.4
19556  201520      2131                     INGI      ING1120   3.1
19557  201520      2131                     INGI      ING1131   3.6
19558  201520      2131                     INGI      ING1310   2.8
19559  201520      2131                     INGI      ING1610   5.1
19560  201520      1964                     INGC      ING1111   4.3
19561  201520      1964                     INGC      ING1131   3.5
19562  201520      1964                     INGC      ING1140   3.5
19563  201520      1964                     INGC      ING1310   5.8
19564  201520      1964                     INGC      ING1610   4.8
19565  201520      2006                     INGE      ING1131   4.0
19566  201520      2006                     INGE      ING1140   4.0

[19567 rows x 5 columns]

Asignamos indentificadores para todos los campos no numéricos(aparte del cluster), y luego los transformamos en campos numericos.

In [5]:
periods = list(dataframe['Periodo'].unique())
courses = list(dataframe['Codigo curso'].unique())
dataframe['Periodo'] = dataframe['Periodo'].apply(periods.index)
dataframe['Codigo curso'] = dataframe['Codigo curso'].apply(courses.index)

            ID Especialidad del momento
0          135                     INGE
1          916                     INGO
2          816                     INGO
3       138126                     INGI
4       931535                     INGI
5      6615148                     INGO
6          695                     INGO
7      7164276                     INGE
8      9405046                     INGI
9     13078358                     INGO
10    13669596                     INGI
11    14434937                     INGI
12    14484286                     INGO
13    14488006                     INGI
14    15049129                     INGI
15    15578246                     INGI
16         457                     INGI
17    15587826                     INGI
18         294                     INGI
19         735                     INGO
20         789                     INGI
21         349                     INGI
22         153                     INGO
23    16525455                     INGI
24         537                     INGI
25         806                     INGI
26    17149882                     INGO
27         568                     INGO
28         637                     INGI
29         391                     INGI
...        ...                      ...
1155      1924                     INGI
1156      1697                     INGI
1157      1875                     INGI
1158      1959                     INGO
1159      1968                     INGI
1160      1702                     INGI
1161      1964                     INGC
1162      2006                     INGE
1163      2062                     INGC
1164      2007                     INGI
1165      1920                     INGI
1166      2029                     INGC
1167      1921                     INGI
1168      1966                     INGI
1169      1976                     INGI
1170      2116                     INGI
1171      2129                     INGO
1172      2124                     INGC
1173      2118                     INGI
1174      2117                     INGI
1175      2132                     INGI
1176      2126                     INGO
1177      2130                     INGI
1178      2121                     INGC
1179      2123                     INGC
1180      2120                     INGO
1181      2122                     INGI
1182      2140                     INGO
1183      2119                     INGC
1184      2131                     INGI

[1185 rows x 2 columns]

In [ ]:
results = dataframe.drop_duplicates(subset=['ID','Especialidad del momento']).drop(columns=['Periodo','Codigo curso', 'Nota']).reset_index().drop(columns='index')
students = list(dataframe['ID'].unique())
finaldataframe = pd.DataFrame(columns=['ID'])
print(df.loc[(df['column_name'] == some_value)